# Generated by Django 3.0.6 on 2022-12-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20221222_1330'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
    ]
